name: Process Metadata

on:
  push:
    branches:
      - main

jobs:
  extract_metadata:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Extract and Transform Metadata
      run: node extract-metadata.js

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update metadata collection: $(date +'%Y-%m-%d %H:%M:%S')"
        git push
